In [3]:
import pandas as pd
file_path = '/Users/xiaoyufan/Desktop/5311/hw1/Street_Tree_List-2022-01-30_FILTERED.csv'
df = pd.read_csv(file_path)
df

,TreeID,qLegalStatus,qSpecies,qAddress,SiteOrder,qSiteInfo,qCaretaker,PlantDate,DBH,PlotSize,Latitude,Longitude
0,200311,DPW Maintained,Liquidambar styraciflua 'Rotundiloba' :: Round...,300 Spear St,9.0,Sidewalk: Curb side : Yard,Private,NaN,5,NaN,37.789193,-122.390006
1,10425,DPW Maintained,Schinus terebinthifolius :: Brazilian Pepper,1419 Haight St,2.0,Sidewalk: Curb side : Cutout,DPW,NaN,90,3x3,37.770094,-122.445693
2,43163,DPW Maintained,Acacia melanoxylon :: Blackwood Acacia,222 Madison St,1.0,Sidewalk: Curb side : Cutout,Private,7/11/00 0:00,8,NaN,37.726036,-122.422690
3,188921,DPW Maintained,Callistemon citrinus :: Lemon Bottlebrush,2001 25th St,16.0,Sidewalk: Property side : Yard,Private,NaN,6,Width 8ft,37.751955,-122.399482
4,643,DPW Maintained,Ficus microcarpa :: Chinese Banyan,3224 24th St,1.0,Sidewalk: Curb side : Cutout,Private,NaN,18,3x3,37.752398,-122.416772
...,...,...,...,...,...,...,...,...,...,...,...,...
37113,141243,DPW Maintained,Magnolia grandiflora :: Southern Magnolia,31 COMMONWEALTH AVE,1.0,Sidewalk: Curb side : Yard,Private,NaN,10,Width 0ft,37.785434,-122.455909
37114,203553,DPW Maintained,Agonis flexuosa :: Peppermint Willow,259 Faxon Ave,1.0,Sidewalk: Curb side : Cutout,Private,NaN,2,Width 3ft,37.719278,-122.460296
37115,61778,DPW Maintained,Eriobotrya deflexa :: Bronze Loquat,2219 24th St,1.0,Sidewalk: Curb side : Cutout,Private,1/22/85 0:00,13,NaN,37.753203,-122.401882
37116,190242,DPW Maintained,Ficus microcarpa nitida 'Green Gem' :: Indian ...,60 New Montgomery St,3.0,Sidewalk: Curb side : Pot,Private,NaN,2,Width 3ft,37.788459,-122.401854
37117,192307,DPW Maintained,Fraxinus spp :: Ash Spp,100 De Haro St,1.0,Sidewalk: Curb side : Cutout,Private,NaN,12,Width 4ft,37.767303,-122.401956

In [20]:
type_counts = df['qSpecies'].value_counts()
filtered_counts1 = type_counts[type_counts > 500 ]
filtered_counts2 = type_counts[(type_counts > 100) & (type_counts < 500)]
filtered_counts3 = type_counts[(type_counts < 100)]
print(filtered_counts1)
print(filtered_counts2)
print(filtered_counts3)


num_filtered_types1 = len(filtered_counts1)
print("Number of unique types after filtering:", num_filtered_types1)
num_filtered_types2 = len(filtered_counts2)
print("Number of unique types after filtering:", num_filtered_types2)
num_filtered_types3 = len(filtered_counts3)
print("Number of unique types after filtering:", num_filtered_types3)
# unique_types_count = df['qSpecies'].nunique()
# print("Number of unique types:", unique_types_count)

# unique_types = df['qSpecies'].unique()
# print("Unique types:", unique_types)

qSpecies
Platanus x hispanica :: Sycamore: London Plane                               2633
Metrosideros excelsa :: New Zealand Xmas Tree                                1937
Lophostemon confertus :: Brisbane Box                                        1727
Pittosporum undulatum :: Victorian Box                                       1669
Tristaniopsis laurina :: Swamp Myrtle                                        1577
Ficus microcarpa nitida 'Green Gem' :: Indian Laurel Fig Tree 'Green Gem'    1425
Magnolia grandiflora :: Southern Magnolia                                    1377
Prunus cerasifera :: Cherry Plum                                             1306
Arbutus 'Marina' :: Hybrid Strawberry Tree                                   1063
Prunus serrulata 'Kwanzan' :: Kwanzan Flowering Cherry                        841
Acacia melanoxylon :: Blackwood Acacia                                        820
Olea europaea :: Olive Tree                                                   789
Corymbia ficifolia :: Red Flowering Gum                                       782
Maytenus boaria :: Mayten                                                     766
Callistemon citrinus :: Lemon Bottlebrush                                     685
Ginkgo biloba :: Maidenhair Tree                                              662
Pyrus calleryana :: Ornamental Pear                                           603
Ulmus parvifolia :: Chinese Elm                                               558
Name: count, dtype: int64
qSpecies
Ligustrum lucidum :: Glossy Privet                                      481
Eriobotrya deflexa :: Bronze Loquat                                     466
Pinus radiata :: Monterey Pine                                          426
Pyrus kawakamii :: Evergreen Pear                                       384
Cordyline australis :: Dracena Palm                                     373
Prunus serrulata :: Ornamental Cherry                                   370
Pittosporum crassifolium :: Karo Tree                                   360
Tristania conferta ::                                                   349
Cupressus macrocarpa :: Monterey Cypress                                344
Juniperus chinensis :: Juniper                                          344
Liquidambar styraciflua :: American Sweet Gum                           329
Tristaniopsis laurina 'Elegant' :: Small-leaf Tristania 'Elegant'       327
Myoporum laetum :: Myoporum                                             316
Ficus retusa nitida :: Banyan Fig                                       311
Melaleuca quinquenervia :: Cajeput                                      310
Ficus nitida :: Laurel Fig                                              276
Washingtonia robusta :: Mexican Fan Palm                                232
Lagunaria patersonii :: Primrose Tree                                   227
Phoenix canariensis :: Canary Island Date Palm                          210
Schinus terebinthifolius :: Brazilian Pepper                            208
Agonis flexuosa :: Peppermint Willow                                    199
Eucalyptus polyanthemos :: Silver Dollar Eucalyptus                     197
Magnolia grandiflora 'Little Gem' :: Little Gem Magnolia                194
Jacaranda mimosifolia :: Jacaranda                                      192
Laurus nobilis :: Sweet Bay: Grecian Laurel                             189
Syagrus romanzoffianum :: Queen Palm                                    187
Acer rubrum :: Red Maple                                                186
Callistemon viminalis :: Weeping Bottlebrush                            172
Ceratonia siliqua :: Carob                                              171
Ficus microcarpa :: Chinese Banyan                                      160
Eucalyptus sideroxylon :: Red Ironbark                                  150
Arbutus unedo :: Strawberry Tree                                        137
Crataegus phaenopyrum :: Washington Hawthorn                            127
Acacia baileyana :: Bailey's Acacia                                     124
Fraxinus uhdei :: Shamel Ash: Evergreen Ash                             117
Quercus agrifolia :: Coast Live Oak                                     114
Syzygium paniculatum :: Brush Cherry                                    111
Afrocarpus gracilior :: Fern Pine                                       109
Rhamnus alaternus :: Italian Buckthorn                                  108
Lyonothamnus floribundus subsp. asplenifolius :: Santa Cruz Ironwood    108
Leptospermum scoparium :: New Zealand Tea Tree                          106
Yucca gloriosa :: Spanish Dagger                                        102
Rhaphiolepis Majestic Beauty :: Indian Hawthorn  'Majestic Beau'        102
Acer palmatum :: Japanese Maple                                         101
Name: count, dtype: int64
qSpecies
Pistacia chinensis :: Chinese Pistache                               97
Taxus baccata :: Irish Yew                                           96
Eucalyptus globulus :: Blue Gum                                      94
Ulmus pumila :: Siberian Elm                                         89
Acer buergeranum :: Trident Maple                                    89
                                                                     ..
Archontophoenix myolensis :: Myola palm                               1
Pinus torreyana :: Torrey Pine                                        1
Diospyros kaki :: Persimmon                                           1
Prunus sargentii 'Columnaris' :: Sargent Cherry Tree 'Columnaris'     1
Platanus x hispanica 'Bloodgood' :: Bloodgood London Plane            1
Name: count, Length: 356, dtype: int64
Number of unique types after filtering: 18
Number of unique types after filtering: 44
Number of unique types after filtering: 356

In [12]:
LegalStatus_counts = df['qLegalStatus'].value_counts()
print(LegalStatus_counts)

qLegalStatus
DPW Maintained                     33931
Permitted Site                      1897
Undocumented                         760
Planning Code 138.1 required         200
Significant Tree                     115
Section 806 (d)                       66
Private                               61
Prune Opt Out                         23
Section 143                           22
Property Tree                         18
Landmark tree                          9
Street Tree Maintenance Opt Out        7
Name: count, dtype: int64

In [14]:
Caretaker_counts = df['qCaretaker'].value_counts()
print(Caretaker_counts)

qCaretaker
Private                    29920
DPW                         6494
SFUSD                        201
Port                         165
Rec/Park                     110
PUC                           47
DPW for City Agency           31
Purchasing Dept               24
Fire Dept                     20
Dept of Real Estate           20
Police Dept                   14
MTA                           14
Health Dept                   12
Mayor Office of Housing       11
Arts Commission                9
Public Library                 8
Housing Authority              5
Office of Mayor                4
City College                   4
Mission Verde                  2
War Memorial                   2
Asian Arts Commission          1
Name: count, dtype: int64

In [23]:
DBH_counts = df['DBH'].value_counts()
print(DBH_counts)
filteredDBH_counts1 = DBH_counts[DBH_counts > 500]
print(filteredDBH_counts)
filteredDBH_counts2 = DBH_counts[(DBH_counts < 500) & (DBH_counts > 100)]
print(filteredDBH_counts2)
filteredDBH_counts3 = DBH_counts[DBH_counts < 100]
print(filteredDBH_counts3)

DBH
3      6264
6      2898
12     2895
5      2285
4      2264
       ...
63        1
69        1
76        1
151       1
66        1
Name: count, Length: 90, dtype: int64
DBH
3     6264
6     2898
12    2895
5     2285
4     2264
8     1980
7     1868
2     1767
10    1534
9     1476
1     1418
11    1197
14    1084
13    1070
18    1067
15     891
16     766
17     508
Name: count, dtype: int64
DBH
20    424
24    386
19    275
30    241
25    220
21    214
22    201
0     191
23    154
36    127
40    110
45    107
35    103
26    101
Name: count, dtype: int64
DBH
28     92
60     83
27     74
50     73
90     62
70     62
42     59
48     58
32     44
29     43
31     40
80     38
100    27
34     26
37     24
33     24
65     18
39     17
46     16
38     15
43     14
56     10
41     10
44     10
55     10
75     10
125     8
47      7
53      5
57      5
49      4
54      4
52      4
85      3
73      3
51      3
88      2
64      2
68      2
74      2
61      2
71      1
79      1
105     1
99      1
67      1
130     1
58      1
95      1
135     1
59      1
94      1
78      1
63      1
69      1
76      1
151     1
66      1
Name: count, dtype: int64

In [31]:
SiteOrder_counts = df['SiteOrder'].value_counts()
print(SiteOrder_counts)
filteredSiteOrder_counts1 = SiteOrder_counts[SiteOrder_counts > 500]
print(filteredSiteOrder_counts1)
filteredSiteOrder_counts2 = SiteOrder_counts[(SiteOrder_counts <= 500) & (SiteOrder_counts > 100)]
print(filteredSiteOrder_counts2)
filteredSiteOrder_counts3 = SiteOrder_counts[(SiteOrder_counts <= 100) & (SiteOrder_counts > 10)]
print(filteredSiteOrder_counts3)
filteredSiteOrder_counts4 = SiteOrder_counts[(SiteOrder_counts <= 10)]
print(filteredSiteOrder_counts4)

SiteOrder
1.0      17232
2.0       6527
3.0       3438
4.0       2168
5.0       1404
         ...
124.0        1
122.0        1
107.0        1
97.0         1
118.0        1
Name: count, Length: 112, dtype: int64
SiteOrder
1.0    17232
2.0     6527
3.0     3438
4.0     2168
5.0     1404
6.0     1056
7.0      787
8.0      590
9.0      502
Name: count, dtype: int64
SiteOrder
10.0    397
11.0    314
12.0    275
13.0    239
14.0    163
15.0    158
16.0    146
17.0    118
Name: count, dtype: int64
SiteOrder
20.0    98
19.0    97
18.0    96
21.0    73
22.0    63
23.0    62
24.0    53
25.0    46
27.0    43
26.0    42
30.0    38
29.0    36
31.0    35
33.0    33
36.0    28
28.0    28
35.0    25
34.0    24
40.0    21
44.0    20
41.0    20
39.0    19
38.0    19
37.0    18
32.0    18
52.0    18
48.0    18
46.0    17
42.0    17
43.0    17
45.0    17
54.0    17
56.0    15
49.0    14
59.0    13
53.0    13
60.0    13
57.0    12
47.0    12
65.0    11
55.0    11
Name: count, dtype: int64
SiteOrder
73.0     10
63.0     10
61.0      9
50.0      9
51.0      9
67.0      8
62.0      8
66.0      8
69.0      7
68.0      6
64.0      5
77.0      5
74.0      5
58.0      5
79.0      5
91.0      4
71.0      4
76.0      4
72.0      4
78.0      3
90.0      3
0.0       3
70.0      3
116.0     3
92.0      2
82.0      2
93.0      2
75.0      2
112.0     2
89.0      2
84.0      2
83.0      2
86.0      2
117.0     2
109.0     2
111.0     2
87.0      2
88.0      2
81.0      1
110.0     1
94.0      1
100.0     1
106.0     1
114.0     1
102.0     1
105.0     1
85.0      1
115.0     1
80.0      1
124.0     1
122.0     1
107.0     1
97.0      1
118.0     1
Name: count, dtype: int64

In [52]:
PlotSize_counts = df['PlotSize'].value_counts()
print(PlotSize_counts)

PlotSize
Width 3ft    8588
3x3          4806
Width 0ft    3885
Width 4ft    3364
3X3          3049
             ...
5x2.5           1
6x18            1
3c3             1
10x8            1
8x7             1
Name: count, Length: 252, dtype: int64

In [65]:
# SiteInfo_counts = df['qSiteInfo'].value_counts()
# print(SiteInfo_counts)

df_sidewalk = df[df['qSiteInfo'].isin(['Sidewalk: Curb side : Cutout', 
                                         'Sidewalk: Property side : Yard', 
                                         'Sidewalk: Curb side : Yard', 
                                         'Sidewalk: Curb side : Pot',
                                         'Sidewalk: Property side : Cutout',
                                         'Sidewalk: Property side : Pot'])]

# df_sidewalk

SiteInfo_counts_sidewalk = df_sidewalk['qSiteInfo'].value_counts()
print(SiteInfo_counts_sidewalk)


# Platanus x hispanica :: Sycamore: London Plane                               2633
# Metrosideros excelsa :: New Zealand Xmas Tree                                1937
# Lophostemon confertus :: Brisbane Box                                        1727
# Pittosporum undulatum :: Victorian Box                                       1669
# Tristaniopsis laurina :: Swamp Myrtle                                        1577
# Ficus microcarpa nitida 'Green Gem' :: Indian Laurel Fig Tree 'Green Gem'    1425
# Magnolia grandiflora :: Southern Magnolia    



columns_to_delete = ['qLegalStatus', 'qAddress', 'SiteOrder', 'qCaretaker', 'PlantDate', 'DBH', 'PlotSize']
df_final = df_sidewalk.drop(columns=columns_to_delete)
print(df_final)
df_final.to_csv('/Users/xiaoyufan/Desktop/5311/hw1/further_processed_data.csv', index=False)

qSiteInfo
Sidewalk: Curb side : Cutout        29158
Sidewalk: Property side : Yard       2699
Sidewalk: Curb side : Yard           2166
Sidewalk: Curb side : Pot             432
Sidewalk: Property side : Cutout      133
Sidewalk: Property side : Pot           3
Name: count, dtype: int64
Average DBH: Curb_Cutout 9.659167295424925
Average DBH: Curb_Pot 7.618055555555555
Average DBH: Curb_Yard 9.767774699907664
Average DBH: Property_Cutout 9.977443609022556
Average DBH: Property_Pot 19.0
Average DBH: Property_Yard 10.359021859948129
       TreeID                                           qSpecies  \
0      200311  Liquidambar styraciflua 'Rotundiloba' :: Round...
1       10425       Schinus terebinthifolius :: Brazilian Pepper
2       43163             Acacia melanoxylon :: Blackwood Acacia
3      188921          Callistemon citrinus :: Lemon Bottlebrush
4         643                 Ficus microcarpa :: Chinese Banyan
...       ...                                                ...
37113  141243          Magnolia grandiflora :: Southern Magnolia
37114  203553               Agonis flexuosa :: Peppermint Willow
37115   61778                Eriobotrya deflexa :: Bronze Loquat
37116  190242  Ficus microcarpa nitida 'Green Gem' :: Indian ...
37117  192307                            Fraxinus spp :: Ash Spp

                            qSiteInfo   Latitude   Longitude
0          Sidewalk: Curb side : Yard  37.789193 -122.390006
1        Sidewalk: Curb side : Cutout  37.770094 -122.445693
2        Sidewalk: Curb side : Cutout  37.726036 -122.422690
3      Sidewalk: Property side : Yard  37.751955 -122.399482
4        Sidewalk: Curb side : Cutout  37.752398 -122.416772
...                               ...        ...         ...
37113      Sidewalk: Curb side : Yard  37.785434 -122.455909
37114    Sidewalk: Curb side : Cutout  37.719278 -122.460296
37115    Sidewalk: Curb side : Cutout  37.753203 -122.401882
37116       Sidewalk: Curb side : Pot  37.788459 -122.401854
37117    Sidewalk: Curb side : Cutout  37.767303 -122.401956

[34591 rows x 5 columns]

In [67]:
df_Curb_Cutout = df[df['qSiteInfo'].isin(['Sidewalk: Curb side : Cutout'])]

type_Curb_Cutout = df_Curb_Cutout['qSpecies'].value_counts()

# print(type_Curb_Cutout)
# Sidewalk: Curb side : Cutout        29158

# Platanus x hispanica :: Sycamore: London Plane                2411
# Metrosideros excelsa :: New Zealand Xmas Tree                 1644
# Lophostemon confertus :: Brisbane Box                         1566
# Pittosporum undulatum :: Victorian Box                        1478
# Tristaniopsis laurina :: Swamp Myrtle                         1438

average_DBH_Curb_Cutout = df_Curb_Cutout['DBH'].mean()

# Display the average DBH
print("Average DBH: Curb_Cutout", average_DBH_Curb_Cutout)

Curb_Cutout = {'name': ['Sycamore: London Plane', 
                        'New Zealand Xmas Tree', 'Brisbane Box', 
                        'Victorian Box', 'Swamp Myrtle'],
        'number': [2411, 1644, 1566, 1478, 1438]}

df_type_cc = pd.DataFrame(Curb_Cutout)
df_type_cc.to_csv('/Users/xiaoyufan/Desktop/5311/hw1/Curb_Cutout.csv', index=False)

####################################

Average DBH: Curb_Cutout 9.659167295424925

In [68]:

df_Curb_Pot = df[df['qSiteInfo'].isin(['Sidewalk: Curb side : Pot'])]

type_Curb_Pot = df_Curb_Pot['qSpecies'].value_counts()

# print(type_Curb_Pot)
# Sidewalk: Curb side : Pot             432
# Ficus microcarpa nitida 'Green Gem' :: Indian Laurel Fig Tree 'Green Gem'    84
# Metrosideros excelsa :: New Zealand Xmas Tree                                24
# Syagrus romanzoffianum :: Queen Palm                                         17
# Juniperus chinensis :: Juniper                                               14
# Olea europaea :: Olive Tree                                                  13

average_DBH_Curb_Pot = df_Curb_Pot['DBH'].mean()

# Display the average DBH
print("Average DBH: Curb_Pot", average_DBH_Curb_Pot)




Curb_Pot = {'name': ['Indian Laurel Fig Tree \'Green Gem\'', 
                        'New Zealand Xmas Tree', 'Queen Palm', 
                        'Juniper ', 'Olive Tree'],
        'number': [84, 24, 17, 14, 13]}

df_type_cp = pd.DataFrame(Curb_Pot)
df_type_cp.to_csv('/Users/xiaoyufan/Desktop/5311/hw1/Curb_Pot.csv', index=False)
####################################

Average DBH: Curb_Pot 7.618055555555555

In [69]:

df_Curb_Yard = df[df['qSiteInfo'].isin(['Sidewalk: Curb side : Yard'])]

type_Curb_Yard = df_Curb_Yard['qSpecies'].value_counts()

# print(type_Curb_Yard)
# Sidewalk: Curb side : Yard           2166
# Metrosideros excelsa :: New Zealand Xmas Tree     185
# Prunus cerasifera :: Cherry Plum                  135
# Platanus x hispanica :: Sycamore: London Plane    120
# Acacia melanoxylon :: Blackwood Acacia            116
# Corymbia ficifolia :: Red Flowering Gum            74

average_DBH_Curb_Yard = df_Curb_Yard['DBH'].mean()

# Display the average DBH
print("Average DBH: Curb_Yard", average_DBH_Curb_Yard)



Curb_Yard = {'name': ['New Zealand Xmas Tree', 
                        'Cherry Plum', 'Sycamore: London Plane', 
                        'Blackwood Acacia', 'Red Flowering Gum'],
        'number': [185, 135, 120, 116, 74]}

df_type_cy = pd.DataFrame(Curb_Yard)
df_type_cy.to_csv('/Users/xiaoyufan/Desktop/5311/hw1/Curb_Yard.csv', index=False)
####################################

Average DBH: Curb_Yard 9.767774699907664

In [5]:
import pandas as pd
file_path = '/Users/xiaoyufan/Desktop/5311/hw1/Street_Tree_List-2022-01-30_FILTERED.csv'
df = pd.read_csv(file_path)
df

df_Property_Cutout = df[df['qSiteInfo'].isin(['Sidewalk: Property side : Cutout'])]

type_Property_Cutout = df_Property_Cutout['qSpecies'].value_counts()

# print(type_Property_Cutout)
# Sidewalk: Property side : Cutout      133
# Arbutus 'Marina' :: Hybrid Strawberry Tree                                   9
# Magnolia grandiflora :: Southern Magnolia                                    9
# Pittosporum undulatum :: Victorian Box                                       8
# Corymbia ficifolia :: Red Flowering Gum                                      7
# Metrosideros excelsa :: New Zealand Xmas Tree                                5
# Juniperus chinensis :: Juniper                                               5
# Leptospermum scoparium 'Ruby Glow' :: New Zealand Ruby Glow Tea Tree         4
# Alnus rhombifolia :: White Alder                                             4
# Ficus nitida :: Laurel Fig                                                   4
# Shrub :: Shrub                                                               4
# Cupressus macrocarpa :: Monterey Cypress                                     3
# Tristaniopsis laurina :: Swamp Myrtle                                        3
# Ficus microcarpa nitida 'Green Gem' :: Indian Laurel Fig Tree 'Green Gem'    3
# Ficus Spp. ::                                                                3
# Platanus x hispanica :: Sycamore: London Plane                               3
# Acacia melanoxylon :: Blackwood Acacia                                       3

average_DBH_Property_Cutout = df_Property_Cutout['DBH'].mean()

# Display the average DBH
print("Average DBH: Property_Cutout", average_DBH_Property_Cutout)

Property_Cutout = {'name': ['Hybrid Strawberry Tree', 
                        'Southern Magnolia', 'Victorian Box', 
                        'Red Flowering Gum', 'New Zealand Xmas Tree'],
        'number': [9, 9, 8, 7, 5]}

df_type_pc = pd.DataFrame(Property_Cutout)
df_type_pc.to_csv('/Users/xiaoyufan/Desktop/5311/hw1/Property_Cutout.csv', index=False)

Average DBH: Property_Cutout 9.977443609022556

In [6]:
df_Property_Pot = df[df['qSiteInfo'].isin(['Sidewalk: Property side : Pot'])]
# df_Property_Pot
type_Property_Pot = df_Property_Pot['qSpecies'].value_counts()

# print(type_Property_Pot)
# Sidewalk: Property side : Pot           3
# Juniperus chinensis :: Juniper    2
# Butia capitata :: Pindo Palm      1

average_DBH_Property_Pot = df_Property_Pot['DBH'].mean()

# Display the average DBH
print("Average DBH: Property_Pot", average_DBH_Property_Pot)


Property_Pot = {'name': ['Juniper', 'Pindo Palm'],
        'number': [2, 1]}

df_type_pp = pd.DataFrame(Property_Pot)
df_type_pp.to_csv('/Users/xiaoyufan/Desktop/5311/hw1/Property_Pot.csv', index=False)

Average DBH: Property_Pot 19.0

In [8]:
df_Property_Yard = df[df['qSiteInfo'].isin(['Sidewalk: Property side : Yard'])]

type_Property_Yard = df_Property_Yard['qSpecies'].value_counts()

# print(type_Property_Yard)
# Sidewalk: Property side : Yard       2699
# Juniperus chinensis :: Juniper                                          262
# Pittosporum crassifolium :: Karo Tree                                   143
# Pinus radiata :: Monterey Pine                                          132
# Cupressus macrocarpa :: Monterey Cypress                                123
# Acacia melanoxylon :: Blackwood Acacia                                   94

average_DBH_Property_Yard = df_Property_Yard['DBH'].mean()

# Display the average DBH
print("Average DBH: Property_Yard", average_DBH_Property_Yard)


Property_Yard = {'name': ['Juniper', 
                        'Karo Tree', 'Monterey Pine', 
                        'Monterey Cypress', 'Blackwood Acacia'],
        'number': [262, 143, 132, 123, 94]}

df_type_py = pd.DataFrame(Property_Yard)
df_type_py.to_csv('/Users/xiaoyufan/Desktop/5311/hw1/Property_Yard.csv', index=False)

Average DBH: Property_Yard 10.359021859948129